name: Validate Branch Name

on:
  pull_request:
    branches:
      - main  # Protegendo a branch main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          if [[ ! $BRANCH_NAME =~ ^feature\/.+ ]]; then
            echo "❌ Pull Request rejected: Branch name must follow the pattern 'feature/{branch_name}'"
            exit 1
          fi
